### ISSUE TITLE
How to tell if an input has focus?

### ISSUE THREAD

**Issue by dave-irvine** [DJanoskova/React-validator-demo#2]
If I have a label that explains what an input is for that I only  want to be visible when that input has focus, how could I achieve this? I can't see a way to tell if an input has focus (although you handle this internally). Would I just need to pass in a `ref` and handle this myself?

**Comment by DJanoskova** [comment]
Hi!

I guess it depends on whatever framework you use. Let's say if you're using `Material UI`, it's quite easy to display some text on focus using the `helperText` attribute from the `TextField` docs - https://material-ui.com/api/text-field/#textfield-api.

If you were to use Material UI then, you could just enhance the `validator.js` (see my enhanced `validatorWithTooltip.js` file that I made and pushed for you - https://github.com/DJanoskova/React-validator-demo/tree/master/src/utils) the way that you also pass a helper text config for your input like this, where the third param is the displayed text -
```
      <TextField
        label="With custom text"
        {...useInput('withCustomText', 'isRequired', 'You\'re focusing me now')}
      />
```

The validator's `useInput` is ready to accept the tooltip param and passes it further -
```
  const useInput = (name, validation, tooltip) =>
    useFormInput({
      name,
      validation,
      tooltip,
      formHandler,
      handleError,
      defaultInvalidAttr: invalidAttr
    });
```

And the `useFormInput` is ready to display it whenever focused by using Material UI's **helper text** attribute -
```
  return {
    value,
    name,
    onChange: handleChange,
    onFocus: handleFocus,
    onBlur: handleBlur,
    helperText: isFocused && tooltip ? tooltip : '',
    ...invalidAttr
  };
```

But this works only because The Material UI's `TextField` is ready to receive this attribute and display it. If you were using some kind of a custom input, I'd suggest wrapping it in a component and handling this logic yourself. You can specify what gets returned in the `useFormInput` hook, so you can make your component work with it, just like Material UI works with **helperText**. Anyway it's up to you what you want to return and append to the input. It's crucial to understand how this hook works, then you can enhance it and do unbelievable magic with it.

FYI I also updated the demo so you can preview the helper text, it's the last section:
https://react-form-hook-validator.herokuapp.com/

Best regards,
Dana
